server:
   port: 4000
   
spring:
   application:
      name: API-GATEWAY
   cloud:
      gateway:
         routes:
           - id: STUDENT-SERVICE
             uri: lb://STUDENT-SERVICE
             predicates:
               - Path=/students/**
             filters:
               - name: CircuitBreaker
                 args:
                   name: STUDENT-SERVICE
                   fallbackuri: forward:/studentServiceFallBack
           - id: FINANCIAL-DEPARTMENT
             uri: lb://FINANCIAL-DEPARTMENT
             predicates:
               - Path=/financial/**
             filters:
               - name: CircuitBreaker
                 args:
                   name: FINANCIAL-DEPARTMENT
                   fallbackuri: forward:/financialDepartmentFallBack
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
      instance:
         hostname: localhost
         
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false